/**
 *
 * $Id$
 */
package ws.tree.validation;

import org.eclipse.emf.common.util.EList;

import ws.tree.Coordinator;
import ws.tree.Root;
import ws.tree.Simulator;

/**
 * A sample validator interface for {@link ws.tree.Tree}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TreeValidator {
	boolean validate();

	boolean validateID(String value);
	boolean validateRoot(Root value);
	boolean validateCoordinator(EList<Coordinator> value);
	boolean validateSimulator(EList<Simulator> value);
}
