/**
 *
 * $Id$
 */
package Model.validation;

import Model.ConfTrans;
import Model.ExtTrans;
import Model.IntTransition;
import Model.Phase;
import Model.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Model.AtomicDEVS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AtomicDEVSValidator {
	boolean validate();

	boolean validateDeltaInt(EList<IntTransition> value);
	boolean validateDeltaConf(EList<ConfTrans> value);
	boolean validateDeltaExt(EList<ExtTrans> value);
	boolean validatePhases(EList<Phase> value);
	boolean validateStateVars(EList<Variable> value);
}
