/**
 *
 * $Id$
 */
package Model.validation;

import Model.Port;

import org.eclipse.emf.ecore.EClassifier;

/**
 * A sample validator interface for {@link Model.Event}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventValidator {
	boolean validate();

	boolean validateTargetPort(Port value);
	boolean validateValue(EClassifier value);
}
