/**
 *
 * $Id$
 */
package Model.validation;

import Model.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Model.Phase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PhaseValidator {
	boolean validate();

	boolean validatePhaseID(String value);
	boolean validateTimeAdvance(double value);
	boolean validatePredicates(EList<Variable> value);
}
