/**
 *
 * $Id$
 */
package rsgf.mw.validation;

import org.eclipse.emf.common.util.EList;

import rsgf.vm.VM;

/**
 * A sample validator interface for {@link rsgf.mw.Middleware}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MiddlewareValidator {
	boolean validate();

	boolean validateProcess(EList<rsgf.bundle.Process> value);
	boolean validateUses(VM value);
}
