/**
 *
 * $Id$
 */
package rsgf.skeleton.validation;

import org.eclipse.emf.common.util.EList;

import rsgf.tree.Root;
import rsgf.tree.Tree;

/**
 * A sample validator interface for {@link rsgf.skeleton.Skeleton}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SkeletonValidator {
	boolean validate();

	boolean validateID(String value);
	boolean validateTree(Tree value);
	boolean validateRootskel(EList<Root> value);
}
